name: CI e2e
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run start
