name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npm i -g @antfu/ni
      - run: corepack enable

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm


      - name: Install dependencies
        run: nci

      - name: Lint
        run: nr lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npm i -g @antfu/ni
      - run: corepack enable

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm


      - name: Install dependencies
        run: nci

      - name: Build
        run: nr build
