name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: main

      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          # Invalidate the cache if the node_modules folder changes
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --code-coverage
      - run: npx nx affected --target=build --parallel=3

      - uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage/apps/app/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
