name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - run: npm i -g @antfu/ni
      - run: corepack enable

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: nci

      - name: Lint
        run: nr lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      
      - run: npm i -g @antfu/ni
      - run: corepack enable

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: nci

      - name: Coverage output folder
        run: mkdir ./coverage

      - name: Test
        run: nr test-ci

      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: Coverage
          path: ./coverage

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: ['test']
    if: always()
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - uses: actions/download-artifact@master
        with:
          name: Coverage
          path: ./coverage

      - name: Coverage
        uses: MishaKav/jest-coverage-comment@main
        with:
          junitxml-title: JUnit
          junitxml-path: ./coverage/junit.xml
          coverage-title: Files coverage
          coverage-path: ./coverage/coverage.txt

  build:
    
    name: Build
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - run: npm i -g @antfu/ni
      - run: corepack enable

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: nci

      - name: Build
        run: nr build

 